cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name

credentials:
  usernames:
    testuser1:
      email: testuser1@gmail.com
      failed_login_attempts: 0
      name: testuser1
      logged_in: true
      password: $2b$12$0ks4HdxIM8r9hWGBjMP3p.OPgBiDXqZ6W8WXJZljrTi81PSq/FyNe
